### ISSUE TITLE
Views aren't updated after the swap

### ISSUE THREAD

**Issue by brycethornton** [shayonj/pg-osc#81]
It appears that views that reference the table being re-written are updated at some point to use the temp `pgosc_op_table...` table but after the swap they continue to reference that temp table, preventing it from being dropped cleanly (you'll get errors mentioning `cannot drop table pgosc_op_table_... because other objects depend on it`).  This appears to be because Postgres stores the view as parsed query tree that keeps a reference to the object identifier instead of just using the name. I found [a StackOverflow post that mentions this ](https://stackoverflow.com/questions/62410923/postgres-view-after-alter-table-to-change-table-name-view-still-queries-it). They mention that using `CREATE OR REPLACE VIEW` can fix this, but we'd have to store the original SQL for the view before the swap and then call `CREATE OR REPLACE VIEW` immediately after the swap to reset it to the original table name.

**Comment by jfrost** [comment]
This is a good callout. We should at least mention this in the [caveats](https://github.com/shayonj/pg-osc#caveats). Any chance you want to make a PR?

**Comment by shayonj** [comment]
Yeah that’s a caveat! I think documentation might have had it at some point. Will add it.

I will try to take a pass it this weekend and see if we can support this feature.

**Comment by shayonj** [comment]
Updated `README` to reflect the caveat.

**Comment by shayonj** [comment]
So, had a chance to think more. Here is a quick summary

I think we can re-create the view in the transaction after we swap the table names [here](https://github.com/shayonj/pg-osc/blob/61f938327e209a1894790ca300787ee2546a158c/lib/pg_online_schema_change/orchestrate.rb#L269-L280). However, the downside here is we could've kept the [exclusive lock open for a while](https://github.com/shayonj/pg-osc/blob/61f938327e209a1894790ca300787ee2546a158c/lib/pg_online_schema_change/orchestrate.rb#L253), basically depending on how long it takes to re-create the view. Which can affect performance/reliability of the app. 

The other option is - instead of re-creating the view from `replay_and_swap!` (like above), it might be worth re-creating it right before [`drop_and_cleanup`](https://github.com/shayonj/pg-osc/blob/61f938327e209a1894790ca300787ee2546a158c/lib/pg_online_schema_change/orchestrate.rb#L69). The assumption here: Having delayed refreshed data within a view is much more preferable than a longer swap time w/ reliability concerns. And, after the views are refreshed, we can successfully drop the old tables too. And if adding/replacing views take a while, thats ok during this part of the proess. 

We can use `pg_get_viewdef` to get the view definition and swap the name of the `op_table*` name with the parent table and perform a `CREATE OR REPLACE VIEW...`

**Comment by jfrost** [comment]
My opinion: Since the whole spirit of pg-osc is to minimize locking during schema changes, we should do the view replacement outside the other transaction so we don't hold that AccessExlusive any longer than necessary. That said, replacing a view should be nearly instantaneous, so I could see the counter argument. My vote is: outside `replay_and_swap` and before `drop_and_cleanup`.

**Comment by brycethornton** [comment]
Thanks once again for the great work!

**Comment by Shohou** [comment]
I'm getting the error saying relation "my_view_name" does not exist. Could it be that script doesn't work correctly with views from another schema?
![image](https://github.com/shayonj/pg-osc/assets/1607593/3433ee3e-a882-4702-95d8-f554c20b6705)
